
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.UIManager;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Juliano
 */
public class TelaConsultaCliente extends javax.swing.JInternalFrame {

     public static String cod;
    
     public void PopularJTable(String sql) {

        String driver = "org.postgresql.Driver";
        String user = "postgres";
        String senha = "senai";
        String url = "jdbc:postgresql://localhost:5432/sesiacademia";
        try {
            Connection con = DriverManager.getConnection(url, user, senha);
            PreparedStatement banco = (PreparedStatement) con.prepareStatement(sql);
            banco.execute(); // cria o vetor

            ResultSet resultado = banco.executeQuery();

            DefaultTableModel model = (DefaultTableModel) tabela.getModel();
            model.setNumRows(0);

            while (resultado.next()) {
                model.addRow(new Object[]{
                    //retorna os dados da tabela do BD, cada campo e um coluna.
                    resultado.getString("cpf"),
                    resultado.getString("nomcli"),
                    resultado.getString("celular"),
                    resultado.getString("nomcat")
                    
                  
                });
            }
            banco.close();
            con.close();
        } catch (SQLException ex) {
            System.out.println("o erro foi " + ex);
        }
    }
     
      private void pegarResolucao() {
        //Faz a tela pegar o tamanho inteiro 
        Toolkit t = Toolkit.getDefaultToolkit();
        Dimension dimensao = t.getScreenSize();
        this.setSize((dimensao.width), (dimensao.height));

        //Elimina as bordas do Frame Interno
        setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI bi = (BasicInternalFrameUI) this.getUI();
        bi.setNorthPane(null); //retirar o painel superior janela.setBorder(null);//retirar bordas

        //Define a cor verde para os padrões
        UIManager.put("nimbusSelectionBackground", new Color(9, 82, 82));//define a cor dos menus da CB
        UIManager.put("nimbusFocus", new Color(9, 82, 82)); //Define a cor das seleções
        UIManager.put("nimbusSelection", new Color(9, 82, 82)); //Define a cor das seleções
        UIManager.put("nimbusInfoBlue", new Color(9, 82, 82)); //Define a cor das seleções
    }
    
    public TelaConsultaCliente() {
        initComponents();
        pegarResolucao();
        
        this.PopularJTable("select a.cpf, a.nomcli, a.celular, b.nomcat from cliente a, categoria b where a.codcat=b.codcat;");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        o = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        estado = new javax.swing.JLabel();
        cpf = new javax.swing.JLabel();
        cliente = new javax.swing.JLabel();
        cidade = new javax.swing.JLabel();
        endereco = new javax.swing.JLabel();
        datnas = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        telefone = new javax.swing.JLabel();
        categoria = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        empresa = new javax.swing.JLabel();
        tipo = new javax.swing.JLabel();
        classi = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        CEP = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        anamnse = new javax.swing.JLabel();
        obs = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        procura = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        musc = new javax.swing.JRadioButton();
        pila = new javax.swing.JRadioButton();
        livre = new javax.swing.JRadioButton();
        todos = new javax.swing.JRadioButton();
        codigo = new javax.swing.JLabel();
        yoga = new javax.swing.JRadioButton();
        func = new javax.swing.JRadioButton();
        conv = new javax.swing.JRadioButton();
        jSeparator1 = new javax.swing.JSeparator();

        jDialog1.setMaximumSize(new java.awt.Dimension(863, 630));
        jDialog1.setMinimumSize(new java.awt.Dimension(863, 630));
        jDialog1.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                jDialog1WindowOpened(evt);
            }
        });

        o.setBackground(new java.awt.Color(255, 255, 255));
        o.setMaximumSize(new java.awt.Dimension(863, 630));
        o.setMinimumSize(new java.awt.Dimension(863, 630));
        o.setPreferredSize(new java.awt.Dimension(863, 630));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(9, 82, 82));
        jLabel2.setText("Estado:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(9, 82, 82));
        jLabel3.setText("CPF:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(9, 82, 82));
        jLabel4.setText("Nome:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(9, 82, 82));
        jLabel5.setText("Cidade:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(9, 82, 82));
        jLabel7.setText("Endereço:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(9, 82, 82));
        jLabel8.setText("Data de Nascimento:");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(9, 82, 82));
        jLabel9.setText("Email:");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(9, 82, 82));
        jLabel10.setText("Telefone:");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(9, 82, 82));
        jLabel12.setText("Categoria");

        estado.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        estado.setText("estado");

        cpf.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cpf.setText("cpf");

        cliente.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cliente.setText("nome");

        cidade.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cidade.setText("cidade");

        endereco.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        endereco.setText("endreco");

        datnas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        datnas.setText("datnas");

        email.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        email.setText("email");

        telefone.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        telefone.setText("tel");

        categoria.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        categoria.setText("cat");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(9, 82, 82));
        jLabel11.setText("Empresa:");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(9, 82, 82));
        jLabel13.setText("Tipo:");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(9, 82, 82));
        jLabel14.setText("Classificação:");

        empresa.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        empresa.setText("emp");

        tipo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tipo.setText("tipo");

        classi.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        classi.setText("class");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(9, 82, 82));
        jLabel16.setText("CEP:");

        CEP.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        CEP.setText("cep");

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sesi_Logo.png"))); // NOI18N
        jLabel17.setText("jLabel17");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(9, 82, 82));
        jLabel18.setText("Informações do Cliente");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(9, 82, 82));
        jLabel6.setText("Anamnese:");

        anamnse.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        anamnse.setText("anamnese");

        obs.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        obs.setForeground(new java.awt.Color(9, 82, 82));
        obs.setText("Observações:");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setText("obs");

        javax.swing.GroupLayout oLayout = new javax.swing.GroupLayout(o);
        o.setLayout(oLayout);
        oLayout.setHorizontalGroup(
            oLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(oLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(oLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(oLayout.createSequentialGroup()
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(160, 160, 160)
                        .addComponent(jLabel18)
                        .addGap(0, 149, Short.MAX_VALUE))
                    .addGroup(oLayout.createSequentialGroup()
                        .addGroup(oLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel8)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(oLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(oLayout.createSequentialGroup()
                                .addComponent(anamnse)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, oLayout.createSequentialGroup()
                                .addGroup(oLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cidade)
                                    .addComponent(datnas)
                                    .addComponent(estado)
                                    .addComponent(cpf)
                                    .addComponent(cliente)
                                    .addComponent(CEP)
                                    .addComponent(endereco))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(oLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(oLayout.createSequentialGroup()
                                        .addGroup(oLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel13)
                                            .addComponent(jLabel11)
                                            .addComponent(jLabel12)
                                            .addComponent(jLabel14)
                                            .addComponent(obs))
                                        .addGap(24, 24, 24)
                                        .addGroup(oLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(empresa)
                                            .addComponent(tipo)
                                            .addComponent(categoria)
                                            .addComponent(classi)
                                            .addComponent(jLabel15)
                                            .addComponent(telefone)))
                                    .addGroup(oLayout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(74, 74, 74)
                                        .addComponent(email)))
                                .addGap(115, 115, 115)))))
                .addGap(103, 103, 103))
        );
        oLayout.setVerticalGroup(
            oLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(oLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(oLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18))
                .addGap(59, 59, 59)
                .addGroup(oLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cliente)
                    .addComponent(jLabel10)
                    .addComponent(telefone))
                .addGap(40, 40, 40)
                .addGroup(oLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cpf)
                    .addComponent(jLabel9)
                    .addComponent(email))
                .addGap(40, 40, 40)
                .addGroup(oLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(estado)
                    .addComponent(tipo)
                    .addComponent(jLabel13))
                .addGap(40, 40, 40)
                .addGroup(oLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cidade)
                    .addComponent(jLabel11)
                    .addComponent(empresa))
                .addGap(40, 40, 40)
                .addGroup(oLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(categoria)
                    .addComponent(jLabel8)
                    .addComponent(datnas))
                .addGap(40, 40, 40)
                .addGroup(oLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(oLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel16)
                        .addComponent(CEP))
                    .addGroup(oLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel14)
                        .addComponent(classi)))
                .addGap(40, 40, 40)
                .addGroup(oLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(endereco)
                    .addComponent(obs)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(oLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(anamnse))
                .addGap(60, 60, 60))
        );

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(o, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(o, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CPF", "Cliente", "Telefone", "Categoria"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabela.setRowHeight(22);
        tabela.setSelectionBackground(new java.awt.Color(50, 194, 128));
        tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tabelaMouseEntered(evt);
            }
        });
        jScrollPane1.setViewportView(tabela);

        procura.setBackground(new java.awt.Color(255, 255, 255));
        procura.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        procura.setForeground(new java.awt.Color(9, 82, 82));
        procura.setText("Procurar");
        procura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                procuraActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(9, 82, 82));
        jLabel1.setText("Categoria:");

        musc.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(musc);
        musc.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        musc.setForeground(new java.awt.Color(9, 82, 82));
        musc.setText("Musculação");

        pila.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(pila);
        pila.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        pila.setForeground(new java.awt.Color(9, 82, 82));
        pila.setText("Pilates");

        livre.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(livre);
        livre.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        livre.setForeground(new java.awt.Color(9, 82, 82));
        livre.setText("Livre");

        todos.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(todos);
        todos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        todos.setForeground(new java.awt.Color(9, 82, 82));
        todos.setText("Todos");

        codigo.setFont(new java.awt.Font("Tahoma", 0, 3)); // NOI18N
        codigo.setForeground(new java.awt.Color(240, 240, 240));
        codigo.setText("jLabel11");

        yoga.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(yoga);
        yoga.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        yoga.setForeground(new java.awt.Color(9, 82, 82));
        yoga.setText("Yoga");

        func.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(func);
        func.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        func.setForeground(new java.awt.Color(9, 82, 82));
        func.setText("Funcional");

        conv.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(conv);
        conv.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        conv.setForeground(new java.awt.Color(9, 82, 82));
        conv.setText("Conx. Bem Estar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(codigo)
                        .addGap(162, 162, 162))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(634, 634, 634))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(func)
                .addGap(66, 66, 66)
                .addComponent(musc)
                .addGap(77, 77, 77)
                .addComponent(conv)
                .addGap(75, 75, 75)
                .addComponent(pila)
                .addGap(81, 81, 81)
                .addComponent(yoga)
                .addGap(95, 95, 95)
                .addComponent(livre)
                .addGap(110, 110, 110)
                .addComponent(todos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(procura)
                .addGap(38, 38, 38))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yoga)
                    .addComponent(pila)
                    .addComponent(livre)
                    .addComponent(todos)
                    .addComponent(conv)
                    .addComponent(musc)
                    .addComponent(func)
                    .addComponent(procura))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMouseClicked
        if(evt.getClickCount()==2){
            int selectedRow = tabela.getSelectedRow();
            DefaultTableModel model = (DefaultTableModel) tabela.getModel();

            cod = model.getValueAt(selectedRow, 0).toString();

            jDialog1.setVisible(true);
            jDialog1.setLocationRelativeTo(null);
            conexao.PesquisaCliente();
          
        }

    }//GEN-LAST:event_tabelaMouseClicked

    private void tabelaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_tabelaMouseEntered

    private void procuraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_procuraActionPerformed
        if (musc.isSelected()) {
            this.PopularJTable("select a.cpf, a.nomcli, a.celular, b.nomcat from cliente a, categoria b where a.codcat=b.codcat and b.nomcat ilike '%Musculacao%'");
        }
        if (pila.isSelected()) {
            this.PopularJTable("select a.cpf, a.nomcli, a.celular, b.nomcat from cliente a, categoria b where a.codcat=b.codcat and b.nomcat ilike '%Pilates%'");
        }
        if (livre.isSelected()) {
            this.PopularJTable("select a.cpf, a.nomcli, a.celular, b.nomcat from cliente a, categoria b where a.codcat=b.codcat and b.nomcat ilike '%Livre%'");
        }
        if (func.isSelected()) {
            this.PopularJTable("select a.cpf, a.nomcli, a.celular, b.nomcat from cliente a, categoria b where a.codcat=b.codcat and b.nomcat ilike '%Funcional%'");
        }
        if (yoga.isSelected()) {
            this.PopularJTable("select a.cpf, a.nomcli, a.celular, b.nomcat from cliente a, categoria b where a.codcat=b.codcat and b.nomcat ilike '%Yoga%'");
        }
        if (conv.isSelected()) {
            this.PopularJTable("select a.cpf, a.nomcli, a.celular, b.nomcat from cliente a, categoria b where a.codcat=b.codcat and b.nomcat ilike '%Conv. Bem Estar%'");
        }

        if (todos.isSelected()) {
            this.PopularJTable("select a.cpf, a.nomcli, a.celular, b.nomcat from cliente a, categoria b where a.codcat=b.codcat");
        }

    }//GEN-LAST:event_procuraActionPerformed

    private void jDialog1WindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jDialog1WindowOpened

    }//GEN-LAST:event_jDialog1WindowOpened


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel CEP;
    public static javax.swing.JLabel anamnse;
    private javax.swing.ButtonGroup buttonGroup1;
    public static javax.swing.JLabel categoria;
    public static javax.swing.JLabel cidade;
    public static javax.swing.JLabel classi;
    public static javax.swing.JLabel cliente;
    public static javax.swing.JLabel codigo;
    private javax.swing.JRadioButton conv;
    public static javax.swing.JLabel cpf;
    public static javax.swing.JLabel datnas;
    public static javax.swing.JLabel email;
    public static javax.swing.JLabel empresa;
    public static javax.swing.JLabel endereco;
    public static javax.swing.JLabel estado;
    private javax.swing.JRadioButton func;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JRadioButton livre;
    private javax.swing.JRadioButton musc;
    public static javax.swing.JPanel o;
    public static javax.swing.JLabel obs;
    private javax.swing.JRadioButton pila;
    private javax.swing.JButton procura;
    private javax.swing.JTable tabela;
    public static javax.swing.JLabel telefone;
    public static javax.swing.JLabel tipo;
    private javax.swing.JRadioButton todos;
    private javax.swing.JRadioButton yoga;
    // End of variables declaration//GEN-END:variables
}
